"""empty message

Revision ID: bd8d37a82153
Revises: 
Create Date: 2024-03-08 17:20:17.204876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8d37a82153'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('file_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('pictures',
    sa.Column('picture_id', sa.Integer(), nullable=False),
    sa.Column('picture_name', sa.String(length=100), nullable=False),
    sa.Column('picture_size', sa.Integer(), nullable=False),
    sa.Column('picture_format', sa.String(length=10), nullable=False),
    sa.Column('picture_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('picture_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('picture_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('picture_id')
    )
    op.create_table('videos',
    sa.Column('videos_id', sa.Integer(), nullable=False),
    sa.Column('videos_name', sa.String(length=100), nullable=False),
    sa.Column('videos_size', sa.Integer(), nullable=False),
    sa.Column('videos_running_time_hour', sa.Integer(), nullable=False),
    sa.Column('videos_running_time_minute', sa.Integer(), nullable=False),
    sa.Column('videos_running_time_second', sa.Integer(), nullable=False),
    sa.Column('videos_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('videos_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('videos_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('videos_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('pictures')
    op.drop_table('files')
    # ### end Alembic commands ###
